### ISSUE TITLE
TouchView

### ISSUE THREAD

**Issue by ferbass** [DavdRoman/Popsicle#18]
I create a simple interpolation between 2 views, but in the first view i have one Button, i need this button can be touched in second view.

I try to set secondView userInteractionEnabled, but have no effect, any idea? 

Thank you

**Comment by DavdRoman** [comment]
Hi there @ferbass.

This issue has appeared in #13, and I believe I provided a neat workaround (I can't really verify it since I got no answer from @hsavit1).

**Comment by ferbass** [comment]
Hi @DavdRoman, this way works great for me 

Thank you
